defaults:
  - /slam: default

instance: vipe.pipeline.panorama.PanoramaAnnotationPipeline

virtual:
  height: 512
  fovx: 100.0
  fovy: 100.0
  num_views: 4
  top: false
  bottom: true

slam:
  buffer: 256
  optimize_intrinsics: false
  keyframe_depth: null
  map_filter_thresh: 0.01

post:
  depth_align_model: unik3d

# Output configs
output:
  # Path to save results
  path: results/
  skip_exists: false

  # Save artifacts and a info file
  save_artifacts: false

  # Visualization videos to BASE_PATH/vipe/xxx.mp4
  save_viz: true
  viz_downsample: 1
  viz_attributes: [["rgb"], ["pcd"]]
